# Generated by Django 3.2.6 on 2021-09-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210914_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commnet_text',
            new_name='comment_text',
        ),
    ]
